[package]
authors = ["pypypypypypypypypyp"]
name = "math_lib"
version = "0.1.0"
edition = "2018"

[features]
serde = ["dep:serde"]
raylib = ["dep:raylib"]

[dependencies]
serde = { version = "1.0.89", features = ["derive"], optional = true }
raylib = { version = "3.7.0", optional = true }
