[package]
authors = ["pypypypypypypypypyp"]
name = "math_lib"
version = "0.1.0"

[dependencies]
serde = "1.0.27"
serde_derive = "1.0.27"

[dependencies.array_tuple]
git = "https://github.com/pypypypypypypypypyp/array_tuple"
