[package]
authors = ["pypypypypypypypypyp"]
name = "math_lib"
version = "0.1.0"
edition = "2018"

[dependencies]
serde = { version = "1.0.89", features = ["derive"] }

[dependencies.array_tuple]
git = "https://github.com/pypypypypypypypypyp/array_tuple"
